export const colorCodeMap: Record<string, Record<string, string>> = {
  toyota: {
    // Whites
    '040': 'Super White',
    '058': 'Storm Trooper',
    '062': 'White Pearl',
    '068': 'Polar Mica Metallic',
    '070': 'White Pearl Crystal Shine',
    '086': 'Liquid Sky',
    '089': 'Wind Chill Pearl',
    '090': 'Oxygen White',
    // Silvers / Grays
    '1D6': 'Silver Sky Metallic',
    '1F7': 'Classic Silver Metallic',
    '1G3': 'Magnetic Gray Metallic',
    '1H1': 'Predawn Gray Mica',
    '1H5': 'Cement Gray',
    '1J9': 'Celestial Silver Metallic',
    '1K3': 'Celestite Gray Metallic',
    '1K4': 'Harbor Gray Metallic',
    '1K5': 'Moondust Metallic',
    '1L5': 'Heavy Metal',
    // Blacks
    '202': 'Black',
    '204': 'Black Metallic',
    '209': 'Black Sand Pearl',
    '212': 'Obsidian',
    '218': 'Attitude Black Mica / Midnight Black Metallic',
    // Reds
    '3R3': 'Barcelona Red Metallic',
    '3T3': 'Ruby Flare Pearl',
    '3U5': 'Supersonic Red',
    '3Q3': 'Salsa Red Pearl',
    '3T5': 'Wildfire',
    // Browns / Beiges
    '4U3': 'Sunset Bronze Metallic',
    '4X4': 'Smoked Mesquite',
    '4X9': 'Opulent Amber',
    // Greens
    '6V7': 'Army Green',
    '6X1': 'Oxide Bronze',
    '6X3': 'Lunar Rock',
    '6X5': 'Cypress',
    // Blues
    '8S6': 'Nautical Blue Metallic',
    '8T6': 'Voodoo Blue',
    '8T7': 'Blue Crush Metallic',
    '8V5': 'Shoreline Blue Pearl',
    '8W2': 'Cavalry Blue',
    '8W7': 'Blue Crush Metallic',
    '8X8': 'Blueprint',
    '8Y7': 'Hydro Blue',
    // JDM codes
    'ZHJ': 'Cafe White Pearl',
    'ZMU': 'Bronze',
  },
  nissan: {
    'A20': 'Code Red Metallic',
    'B17': 'Deep Blue Pearl',
    'B51': 'Electric Blue Metallic',
    'CAJ': 'Java Metallic',
    'EAN': 'MOAB Sunset Metallic',
    'G41': 'Magnetic Black Pearl',
    'GAG': 'Jet Black',
    'K12': 'Radiant Silver Metallic',
    'K23': 'Brilliant Silver Metallic',
    'K26': 'Pearl White',
    'K50': 'Daytona Blue Metallic',
    'K51': 'Caspian Blue Metallic',
    'KAD': 'Gun Metallic',
    'KBY': 'Boulder Gray Pearl',
    'KH3': 'Super Black',
    'NAH': 'Cayenne Red Metallic',
    'NBL': 'Storm Blue Metallic',
    'QAB': 'Brilliant White Pearl / Pearl White',
    'QAK': 'Glacier Pearl',
    'QM1': 'Fresh Powder',
    'QX1': 'Glacier White / Brilliant White Pearl',
    'QX3': 'Satin White Pearl',
    'RAB': 'Deep Blue Pearl Metallic',
    'RAY': 'Deep Blue Pearl',
    'RBD': 'Storm Blue Metallic',
    'RBY': 'Caspian Blue Metallic',
  },
  honda: {
    'B-588P': 'Obsidian Blue Pearl',
    'B-575P': 'Still Night Pearl',
    'B-607M': 'Cosmic Blue Metallic',
    'B-637P': 'Boost Blue Pearl',
    'NH-547': 'Berlina Black',
    'NH-578': 'Taffeta White',
    'NH-603P': 'White Diamond Pearl',
    'NH-700M': 'Alabaster Silver Metallic',
    'NH-701M': 'Galaxy Gray Metallic',
    'NH-731P': 'Crystal Black Pearl',
    'NH-737M': 'Polished Metal Metallic',
    'NH-788P': 'White Orchid Pearl',
    'NH-797M': 'Modern Steel Metallic',
    'NH-830M': 'Lunar Silver Metallic',
    'NH-877P': 'Sonic Gray Pearl',
    'NH-883P': 'Platinum White Pearl',
    'NH-904M': 'Meteorite Gray Metallic',
    'NH-912P': 'Urban Gray Pearl',
    'R-513': 'Rallye Red',
    'R-525P': 'Tango Red Pearl',
    'R-561P': 'Deep Scarlet Pearl',
    'R-569M': 'Radiant Red Metallic',
    'YR-578M': 'Urban Titanium Metallic',
    'YR-604M': 'Golden Brown Metallic',
  },
  suzuki: {
    '26U': 'Superior White',
    'Z2S': 'Silky Silver Metallic',
    'Z7T': 'Pearl White / White Pearl Tricoat',
    'Z9T': 'Bright Red',
    'ZCC': 'Silky Silver II Metallic',
    'ZCD': 'Galactic Gray Metallic',
    'ZCF': 'Bright Red',
    'ZJ3': 'Bluish Black Pearl Metallic / Onyx Black',
    'ZMA': 'Cool Beige Metallic',
    'ZMV': 'Splash Blue Metallic',
    'ZMW': 'Azure Grey Metallic',
    'ZNB': 'Snow White Pearl',
    'ZRJ': 'Stargaze Black Pearl',
    'ZVL': 'Premium Silver Metallic',
    'ZWG': 'Atlantis Turquoise',
    'ZWJ': 'Cerulean Blue',
  },
  mazda: {
    '22V': 'Sunlight Silver Metallic',
    '25D': 'Snowflake White Pearl Mica',
    '32V': 'Copper Red Mica',
    '34K': 'Crystal White Pearl Mica',
    '35J': 'Stormy Blue Mica',
    '38P': 'Liquid Silver Metallic',
    '38R': 'Graphite Mica',
    '39T': 'Dolphin Gray Mica',
    '41V': 'Soul Red Metallic',
    '41W': 'Jet Black Mica',
    '42A': 'Meteor Gray Mica',
    '42M': 'Deep Crystal Blue Mica',
    '42S': 'Titanium Flash Mica',
    '44J': 'Dynamic Blue',
    '45B': 'Eternal Blue Mica',
    '45P': 'Sonic Silver Metallic',
    '46G': 'Machine Gray Metallic',
    '46V': 'Soul Red Crystal Metallic',
    '47C': 'Polymetal Gray Metallic',
    '47S': 'Platinum Quartz Metallic',
    '51K': 'Rhodium White Metallic',
  },
}

export function lookupColorName(brand: string | null | undefined, code: string | null | undefined): string | null {
  if (!brand || !code) return null
  const brandKey = brand.toLowerCase().trim()
  const codeKey = code.toUpperCase().trim()
  const brandMap = colorCodeMap[brandKey]
  if (!brandMap) return null
  if (brandMap[codeKey]) return brandMap[codeKey]
  const found = Object.keys(brandMap).find(k => k.toUpperCase() === codeKey)
  return found ? brandMap[found] : null
}
